"""
Position-specific criteria definitions for MCDM evaluation.
Maps football criteria to CSV column names and specifies benefit/cost types.
"""

# Criteria type: 1 = benefit (higher is better), -1 = cost (lower is better)

POSITION_CRITERIA = {
    "Forward": {
        "xG": {"column": "expected_goals_per90", "type": 1, "label": "Expected Goals (xG)"},
        "Goals": {"column": "goals_scored_per90", "type": 1, "label": "Goals"},
        "Assists": {"column": "assists_per90", "type": 1, "label": "Assists"},
        "Shooting Threat": {"column": "threat_per90", "type": 1, "label": "Shooting Threat"},
        "Creativity": {"column": "creativity_per90", "type": 1, "label": "Creativity"},
        "Defensive Contribution": {"column": "defensive_contribution_per90", "type": 1, "label": "Defensive Work"},
        "Aerial Ability": {"column": "clearances_blocks_interceptions_per90", "type": 1, "label": "Aerial Ability"},
        "Yellow Cards": {"column": "yellow_cards_per90", "type": -1, "label": "Yellow Cards"},
        "Red Cards": {"column": "red_cards_per90", "type": -1, "label": "Red Cards"},
    },
    "Midfielder": {
        "xA": {"column": "expected_assists_per90", "type": 1, "label": "Expected Assists (xA)"},
        "Goals": {"column": "goals_scored_per90", "type": 1, "label": "Goals"},
        "Assists": {"column": "assists_per90", "type": 1, "label": "Assists"},
        "Shooting Threat": {"column": "threat_per90", "type": 1, "label": "Shooting Threat"},
        "Creativity": {"column": "creativity_per90", "type": 1, "label": "Creativity"},
        "Tackles": {"column": "tackles_per90", "type": 1, "label": "Tackles"},
        "Interceptions": {"column": "clearances_blocks_interceptions_per90", "type": 1, "label": "Interceptions"},
        "Yellow Cards": {"column": "yellow_cards_per90", "type": -1, "label": "Yellow Cards"},
        "Red Cards": {"column": "red_cards_per90", "type": -1, "label": "Red Cards"},
    },
    "Defender": {
        "Goals": {"column": "goals_scored_per90", "type": 1, "label": "Goals"},
        "Tackles": {"column": "tackles_per90", "type": 1, "label": "Tackles"},
        "Interceptions": {"column": "clearances_blocks_interceptions_per90", "type": 1, "label": "Interceptions"},
        "Clean Sheets": {"column": "clean_sheets_per90", "type": 1, "label": "Clean Sheets"},
        "Influence": {"column": "influence_per90", "type": 1, "label": "Influence"},
        "Yellow Cards": {"column": "yellow_cards_per90", "type": -1, "label": "Yellow Cards"},
        "Red Cards": {"column": "red_cards_per90", "type": -1, "label": "Red Cards"},
    },
    "Goalkeeper": {
        "Saves": {"column": "saves_per90", "type": 1, "label": "Saves"},
        "Clean Sheets": {"column": "clean_sheets_per90", "type": 1, "label": "Clean Sheets"},
        "Goals Conceded": {"column": "goals_conceded_per90", "type": -1, "label": "Goals Conceded"},
        "Influence": {"column": "influence_per90", "type": 1, "label": "Influence"},
        "Yellow Cards": {"column": "yellow_cards_per90", "type": -1, "label": "Yellow Cards"},
        "Red Cards": {"column": "red_cards_per90", "type": -1, "label": "Red Cards"},
    },
}

# Formation definitions: maps formation string to position slots
FORMATIONS = {
    "4-3-3": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "LB": {"pos": "Defender", "x": 15, "y": 72},
        "CB1": {"pos": "Defender", "x": 37, "y": 75},
        "CB2": {"pos": "Defender", "x": 63, "y": 75},
        "RB": {"pos": "Defender", "x": 85, "y": 72},
        "CM1": {"pos": "Midfielder", "x": 30, "y": 52},
        "CM2": {"pos": "Midfielder", "x": 50, "y": 55},
        "CM3": {"pos": "Midfielder", "x": 70, "y": 52},
        "LW": {"pos": "Forward", "x": 20, "y": 28},
        "ST": {"pos": "Forward", "x": 50, "y": 25},
        "RW": {"pos": "Forward", "x": 80, "y": 28},
    },
    "4-4-2": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "LB": {"pos": "Defender", "x": 15, "y": 72},
        "CB1": {"pos": "Defender", "x": 37, "y": 75},
        "CB2": {"pos": "Defender", "x": 63, "y": 75},
        "RB": {"pos": "Defender", "x": 85, "y": 72},
        "LM": {"pos": "Midfielder", "x": 15, "y": 50},
        "CM1": {"pos": "Midfielder", "x": 37, "y": 53},
        "CM2": {"pos": "Midfielder", "x": 63, "y": 53},
        "RM": {"pos": "Midfielder", "x": 85, "y": 50},
        "ST1": {"pos": "Forward", "x": 37, "y": 25},
        "ST2": {"pos": "Forward", "x": 63, "y": 25},
    },
    "3-5-2": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "CB1": {"pos": "Defender", "x": 25, "y": 75},
        "CB2": {"pos": "Defender", "x": 50, "y": 77},
        "CB3": {"pos": "Defender", "x": 75, "y": 75},
        "LWB": {"pos": "Midfielder", "x": 10, "y": 55},
        "CM1": {"pos": "Midfielder", "x": 32, "y": 52},
        "CM2": {"pos": "Midfielder", "x": 50, "y": 50},
        "CM3": {"pos": "Midfielder", "x": 68, "y": 52},
        "RWB": {"pos": "Midfielder", "x": 90, "y": 55},
        "ST1": {"pos": "Forward", "x": 37, "y": 25},
        "ST2": {"pos": "Forward", "x": 63, "y": 25},
    },
    "4-2-3-1": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "LB": {"pos": "Defender", "x": 15, "y": 72},
        "CB1": {"pos": "Defender", "x": 37, "y": 75},
        "CB2": {"pos": "Defender", "x": 63, "y": 75},
        "RB": {"pos": "Defender", "x": 85, "y": 72},
        "CDM1": {"pos": "Midfielder", "x": 37, "y": 58},
        "CDM2": {"pos": "Midfielder", "x": 63, "y": 58},
        "LAM": {"pos": "Midfielder", "x": 20, "y": 40},
        "CAM": {"pos": "Midfielder", "x": 50, "y": 38},
        "RAM": {"pos": "Midfielder", "x": 80, "y": 40},
        "ST": {"pos": "Forward", "x": 50, "y": 22},
    },
    "3-4-3": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "CB1": {"pos": "Defender", "x": 25, "y": 75},
        "CB2": {"pos": "Defender", "x": 50, "y": 77},
        "CB3": {"pos": "Defender", "x": 75, "y": 75},
        "LM": {"pos": "Midfielder", "x": 15, "y": 52},
        "CM1": {"pos": "Midfielder", "x": 37, "y": 55},
        "CM2": {"pos": "Midfielder", "x": 63, "y": 55},
        "RM": {"pos": "Midfielder", "x": 85, "y": 52},
        "LW": {"pos": "Forward", "x": 20, "y": 28},
        "ST": {"pos": "Forward", "x": 50, "y": 25},
        "RW": {"pos": "Forward", "x": 80, "y": 28},
    },
    "5-3-2": {
        "GK": {"pos": "Goalkeeper", "x": 50, "y": 90},
        "LWB": {"pos": "Defender", "x": 10, "y": 65},
        "CB1": {"pos": "Defender", "x": 30, "y": 75},
        "CB2": {"pos": "Defender", "x": 50, "y": 77},
        "CB3": {"pos": "Defender", "x": 70, "y": 75},
        "RWB": {"pos": "Defender", "x": 90, "y": 65},
        "CM1": {"pos": "Midfielder", "x": 30, "y": 50},
        "CM2": {"pos": "Midfielder", "x": 50, "y": 48},
        "CM3": {"pos": "Midfielder", "x": 70, "y": 50},
        "ST1": {"pos": "Forward", "x": 37, "y": 25},
        "ST2": {"pos": "Forward", "x": 63, "y": 25},
    },
}
